name: moviehub
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  get_cli: ^1.8.1
  get: ^4.6.5
  flutter_test:
    sdk: flutter
  otp_text_field: ^1.1.3
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  dio: ^5.1.2
  youtube_player_flutter: ^8.1.2

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
